server:
  port: 9999

spring:
  profiles:
    active: native
  application:
    name: configuration-server
  cloud:
    config:
      server:
        native:
          search-locations: D:/Download/springO/springO/springschool/configs-lab-3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka
  instance:
    metadata-map:
      instance-id: ${spring.application.name}:${server.port}